include makefiles/Makefile.linux.inc

${TARGET}: ${OBJECTS}
	@echo -e "\tLD    $@"
	$(LINK) $(LIBADD) $(OBJECTS) -o $(TARGET)

libhypnos/libhypnos.a: ${LIBOBJS}
	@echo -e "\tLD    $@"
	$(AR) r libhypnos/libhypnos.a $(LIBOBJS)

include makefiles/Makefile.inc