include makefiles/Makefile.mingw.inc

${TARGET}: ${OBJECTS}
	@echo -e "\tLD    $@"
	$(LINK) $(LIBADD) $(LDFLAGS) $(OBJECTS) -o $(TARGET)
	@echo -e "\tSTRIP $@"
	$(STRIP) --strip-all $(TARGET)

include makefiles/Makefile.inc