include makefiles/Makefile.mingw.inc

${TARGET}.exe: ${OBJECTS}
	@echo -e "\tLD    $@"
	$(LINK) $(LIBADD) $(LDFLAGS) $(OBJECTS) -o $(TARGET)
#	@echo -e "\tSTRIP $@"
#	$(STRIP) --strip-all $(TARGET)

libhypnos/libhypnos.a: ${LIBOBJS}
	@echo -e "\tLD    $@"
	$(AR) r libhypnos/libhypnos.a $(LIBOBJS)

include makefiles/Makefile.inc