CC		=@gcc
CXX		=@g++
LINK		=@g++
STRIP		=@strip

CXXFLAGS	:= $(CXXFLAGS) -mno-cygwin
LDFLAGS		:= $(LDFLAGS) -mno-cygwin

TARGET		= hypnos.exe

include makefiles/Makefile.inc

${TARGET}: ${OBJECTS}
	@echo -e "\tLD    $@"
	$(LINK) $(LIBADD) $(LDFLAGS) $(OBJECTS) -o $(TARGET)
	@echo -e "\tSTRIP $@"
	$(STRIP) --strip-all $(TARGET)
